# Generated by Django 3.0.1 on 2020-07-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=20)),
                ('fees', models.CharField(default='', max_length=10)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('map', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(upload_to='institute_images')),
            ],
            options={
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('fees', models.CharField(max_length=10)),
                ('registration_id', models.CharField(default='', max_length=100, unique=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Institute')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Registration')),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
