# Generated by Django 3.0.1 on 2020-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='txn_amount',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='txn_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='txn_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='txn_msg',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='registration',
            name='txn_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
